apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-socialaccount-providers
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: {{ .Release.Name }}-socialaccount-providers
    creationPolicy: Owner
  data:
    - secretKey: socialaccount-providers
      remoteRef:
        key: paperless_socialaccount_providers
