apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-socialaccount-providers
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: {{ .Release.Name }}-socialaccount-providers
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: paperless-ngx/paperless-ngx-socialaccount-providers
