# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
app-template:
  controllers:
    main:
      type: deployment
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: registry
            tag: "3.1.1@sha256:1be55279f18a2fe1a74edf2664cac61c1bea305b7b4642dab412e7affdcb3e33"
          env:
            REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          ports:
            - name: http
              containerPort: 5000
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 5000
                initialDelaySeconds: 10
                periodSeconds: 30
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 5000
                initialDelaySeconds: 5
                periodSeconds: 10

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 5000

  ingress:
    main:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        traefik.ingress.kubernetes.io/router.middlewares: traefik-ip-allowlist@kubernetescrd
      className: "traefik"
      hosts:
        - host: &host registry.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: registry-tls
          hosts:
            - *host

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      annotations:
        helm.sh/resource-policy: keep
        argocd.argoproj.io/sync-options: Delete=false
      accessMode: ReadWriteOnce
      size: 20Gi
      globalMounts:
        - path: /var/lib/registry
