apiVersion: v2
name: mealie
description: Recipe manager and meal planner
type: application
version: 0.1.0
dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.2.0
  - name: cluster
    alias: cnpg-cluster
    repository: https://cloudnative-pg.github.io/charts
    version: 0.3.1
