---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radicale-radicale-users
data:
  users: |-
    {{- range  .Values.radicale.radicale.auth.users }}
    {{ .username }}:{{ .password }}
    {{- end }}
