apiVersion: v2
name: zitadel
description: Identity infrastructure, simplified for you
type: application
version: 0.1.0
dependencies:
  - name: zitadel
    repository: https://charts.zitadel.com
    version: 8.3.0
    condition: zitadel.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.27
