apiVersion: v2
name: home-assistant
description: Open source home automation that puts local control and privacy first
type: application
version: 0.1.0
dependencies:
  - name: home-assistant
    repository: oci://tccr.io/truecharts
    version: 27.2.3
