# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
app-template:
  controllers:
    client:
      type: deployment
      containers:
        main:
          image:
            repository: ghcr.io/cterence/minecraft-web-client
            tag: next@sha256:3220cda72fe9566f74ae8f98834881740c191db1120d654a585f19a9d0d80ca2
          ports:
            - name: http
              containerPort: 8080
          probes:
            liveness:
              enabled: true
              type: HTTP
            readiness:
              enabled: true
              type: HTTP
    server:
      type: deployment
      containers:
        main:
          image:
            repository: stevesloka/kubecraft
            tag: latest@sha256:b9b2069ec2da8f6610fd1f207df9fbc08e7a08241d44847fbd6230fe401d58fa
          ports:
            - name: minecraft
              containerPort: 25565
          probes:
            liveness:
              enabled: true
              type: TCP
            readiness:
              enabled: true
              type: TCP

  service:
    client:
      controller: client
      type: ClusterIP
      ports:
        http:
          port: 8080
    server:
      controller: server
      type: ClusterIP
      ports:
        http:
          port: 25565

  ingress:
    client:
      enabled: true
      className: "nginx"
      annotations:
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        cert-manager.io/cluster-issuer: letsencrypt
        # nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        # nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
        # nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
      hosts:
        - host: &host minecraft.terence.cloud
          paths:
            - path: /
              pathType: ImplementationSpecific
              service:
                identifier: client
                port: http
      tls:
        - secretName: minecraft-tls
          hosts:
            - *host
