apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-pocket-id-client-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: {{ .Release.Name }}-pocket-id-client-secret
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: immich_pocket_id_client_secret
