apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-pocket-id-client-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: {{ .Release.Name }}-pocket-id-client-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: immich/immich-pocket-id-client-secret
