apiVersion: v2
name: satisfactory-server
description: Satisfactory server
type: application
version: 0.1.0
dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.0.1
  - name: cluster-local
    alias: cnpg-cluster-pg17
    repository: "file://../../charts/cnpg-cluster"
    version: 0.2.1
