keys:
  - &homelab2 age1ky8phu7rmf6yashsrp25ep22yc4nulm7eakss2l764rhf0m4r3tqm0jgz8
  - &homelab3 age1can73zkeq8v9r4a8egrmrnx753jdd2fss9l08jmc8pvh3jyptf2spz20nu
  - &stronghold age1966dt3tnupyte5aw7nggn8cmp2uh498nyjgv08tnxfdc8ur884ysnnq34s
  - &macbook age1uzwuy5steacgyc2rlg00c0snr3tuc3whtfrvkkp3lr9858gmda6q9d7k29
creation_rules:
  - path_regex: terraform/secrets/[^/]+\.(yaml|json|env|ini|toml)$
    key_groups:
      - age:
          - *homelab2
          - *homelab3
          - *stronghold
          - *macbook
