apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-{{ .Release.Namespace }}
  target:
    name: {{ .Release.Name }}
  data:
    - secretKey: DB_CONNECTION_STRING
      remoteRef:
        key: {{ .Release.Name }}-cnpg-cluster-app
        property: uri
    - secretKey: MAXMIND_LICENSE_KEY
      remoteRef:
        key: {{ .Release.Name }}-maxmind-key
        property: maxmind-key
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: {{ .Release.Name }}-encryption-key
        property: encryption-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-maxmind-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: {{ .Release.Name }}-maxmind-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: pocket-id/pocket-id-maxmind-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-encryption-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: {{ .Release.Name }}-encryption-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: pocket-id/pocket-id-encryption-key
