apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 0.1.0
dependencies:
  - name: traefik
    repository: https://traefik.github.io/charts
    version: 41.0.2
  - name: app-template
    alias: modsecurity
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
