traefik:
  deployment:
    enabled: true
    replicas: 1
    additionalVolumes: []
    initContainers:
      - name: wait-for-modsecurity
        image: alpine:latest@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Waiting for modsecurity to be reachable..."
            until nc -z -w 2 modsecurity 8081; do
              echo "modsecurity is unreachable - retrying in 2 seconds..."
              sleep 2
            done
            echo "modsecurity is up and running!"
  experimental:
    abortOnPluginFailure: true
    fastProxy:
      enabled: false
      debug: false
    kubernetesGateway:
      enabled: false
    plugins:
      modsecurity:
        moduleName: github.com/madebymode/traefik-modsecurity-plugin
        version: v1.6.0
      geoblock:
        moduleName: github.com/PascalMinder/geoblock
        version: v0.3.3
      sablier:
        moduleName: github.com/sablierapp/sablier
        version: v1.10.1
    localPlugins: {}
    otlpLogs: false
    knative: false

  volumes: []
  # - name: '{{ printf "%s-configs" .Release.Name }}'
  #   mountPath: "/config"
  #   type: configMap

  additionalVolumeMounts: []
  # -- For instance when using a logshipper for access logs
  # - name: traefik-logs
  #   mountPath: /var/log/traefik

  ports:
    traefik:
      port: 8080
      expose:
        default: false
      exposedPort: 8080
    web:
      port: 8000
      expose:
        default: true
      exposedPort: 80
      forwardedHeaders:
        trustedIPs:
          - 109.0.228.97/32
          - 192.168.1.0/24
          - 10.0.0.0/8
        insecure: false
      proxyProtocol:
        trustedIPs:
          - 109.0.228.97/32
          - 192.168.1.0/24
          - 10.0.0.0/8
        insecure: false
    websecure:
      port: 8443
      expose:
        default: true
      exposedPort: 443
      allowACMEByPass: false
      http3:
        enabled: false
        advertisedPort: # @schema type:[integer, null]; minimum:0
      forwardedHeaders:
        trustedIPs:
          - 192.168.1.0/24
          - 10.0.0.0/8
        insecure: false
      proxyProtocol:
        trustedIPs:
          - 192.168.1.0/24
          - 10.0.0.0/8
        insecure: false
      observability:
        accessLogs: true
      http:
        tls:
          enabled: true
          options: ""
          certResolver: ""
          domains: []
        middlewares:
          - traefik-geoblock@kubernetescrd
          - traefik-secure-headers@kubernetescrd
    metrics:
      port: 9100
      expose:
        default: false
      exposedPort: 9100

  extraObjects:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: ok-server-script
      data:
        index.ts: |
          Bun.serve({ async fetch(req: Request) { if (req.body) { for await (const chunk of req.body); } return new Response("OK", { status: 200 }); }, maxRequestBodySize: Infinity, });
    - apiVersion: traefik.io/v1alpha1
      kind: TLSOption
      metadata:
        name: client-auth
        namespace: cert-manager
      spec:
        clientAuth:
          secretNames:
            - client-auth-ca
          clientAuthType: RequireAndVerifyClientCert
    # Middleware and catch-all ingress route to allow HTTP-01 challenges to succeed by allowing them use of port 80
    - apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: redirect-https
        namespace: traefik
      spec:
        redirectScheme:
          scheme: https
          permanent: true
    - apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: http-catchall
        namespace: traefik
      spec:
        entryPoints:
          - web
        routes:
          - match: PathPrefix(`/`) && !PathPrefix(`/.well-known/acme-challenge/`)
            kind: Rule
            priority: 10000
            middlewares:
              - name: redirect-https
            services:
              - name: traefik
                kind: Service
                port: 80
    - apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: strip-first-path
        namespace: traefik
      spec:
        replacePathRegex:
          regex: "^/[^/]+(/|$)(.*)"
          replacement: "/$2"
    - apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: ip-allowlist
      spec:
        ipAllowList:
          sourceRange:
            - 10.0.0.0/8
            - 192.168.1.0/24
            - 109.0.228.97
            - 34.75.201.84
            - 212.234.168.153
            - 158.178.213.233
            - 145.241.166.205
    - apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: secure-headers
        namespace: traefik
      spec:
        headers:
          browserXssFilter: true
          contentTypeNosniff: true
          customFrameOptionsValue: "SAMEORIGIN"
          forceSTSHeader: true
          frameDeny: true
          referrerPolicy: "strict-origin-when-cross-origin"
          stsIncludeSubdomains: true
          stsPreload: true
          stsSeconds: 15552000
          customResponseHeaders:
            # remove unnecessary headers which expose used server software
            server: ""
            x-powered-by: ""
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: modsecurity-request-exclusion-rules
      data:

    - apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: modsecurity
      spec:
        plugin:
          modsecurity:
            modSecurityUrl: http://modsecurity:8081
            maxBodySize: 1000000000
            timeoutMillis: 120000
            jailEnabled: false
            jailTimeDurationSecs: 600
            badRequestsThresholdCount: 5
            badRequestsThresholdPeriodSecs: 60

  ingressClass:
    enabled: true
    isDefaultClass: true
    name: ""

  api:
    dashboard: true
    basePath: "" # @schema type:[string, null]; default: "/"

  providers:
    # @schema additionalProperties: false
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true
      allowExternalNameServices: true
      allowEmptyServices: true
      ingressClass: ""
      namespaces: []
      nativeLBByDefault: false

    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      allowEmptyServices: true
      ingressClass: # @schema type:[string, null]
      namespaces: []
      publishedService:
        enabled: true
        pathOverride: ""
      nativeLBByDefault: false
      strictPrefixMatching: false

    kubernetesGateway:
      enabled: false

  global:
    checkNewVersion: false
    sendAnonymousUsage: false

  additionalArguments: []
  env:
    - name: TZ
      value: Europe/Paris
  envFrom: []

  tlsOptions: {}
  tlsStore: {}

  service:
    enabled: true
    single: true
    type: LoadBalancer
    spec:
      loadBalancerIP: "192.168.1.241"
      externalTrafficPolicy: Local

  metrics:
    prometheus:
      service:
        enabled: true
      disableAPICheck: true
      serviceMonitor:
        enabled: true
        metricRelabelings:
          - sourceLabels: [__name__]
            separator: ;
            regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
            replacement: $1
            action: drop
        relabelings:
          - sourceLabels: [__meta_kubernetes_pod_node_name]
            separator: ;
            regex: ^(.*)$
            targetLabel: nodename
            replacement: $1
            action: replace
        jobLabel: traefik
        interval: 30s
        honorLabels: true
      prometheusRule:
        enabled: true
        rules:
          - alert: TraefikDown
            expr: up{job="traefik-metrics"} == 0
            for: 5m
            labels:
              context: traefik
              severity: warning
            annotations:
              summary: "Traefik Down"
              description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"

  accessLog:
    enabled: true

modsecurity:
  global:
    fullnameOverride: modsecurity
  configMaps:
    modsecurity-request-exclusion-rules:
      data:
        REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf: |
          <LocationMatch "(?i)^/(audio|videos|api/assets)/">
            RequestHeader unset Range
          </LocationMatch>

          SecRule REQUEST_HEADERS:User-Agent "@rx ^kube-probe/.*$" \
            "id:1000001,phase:1,pass,nolog,ctl:ruleRemoveById=920350"

          SecRule REQUEST_HEADERS:User-Agent "@rx ^GitHub-Hookshot/.*$" \
            "id:1000002,phase:1,pass,nolog,ctl:ruleRemoveById=931130,ctl:ruleRemoveById=932281"

          SecRule REQUEST_URI "@rx ^/api/assets" \
            "id:1000003,phase:1,pass,nolog,ctl:ruleRemoveById=200004"

          SecRule REQUEST_URI "@rx ^/_api/v1/(get-missing-paths|upload-path)" \
            "id:1000004,phase:1,nolog,pass,ctl:requestBodyAccess=Off"

          SecRule REQUEST_URI "(?i)^/audio/" \
            "id:1000005,phase:1,pass,nolog,ctl:ruleEngine=Off"

          SecRule REQUEST_URI "(?i)^/videos/" \
            "id:1000006,phase:1,pass,nolog,ctl:ruleEngine=Off"

          SecRule REQUEST_URI "@rx ^/.well-known/acme-challenge/" \
            "id:1000007,phase:1,pass,nolog,ctl:ruleEngine=Off"

          SecRule REQUEST_URI "@rx ^/api/documents/" \
            "id:1000008,phase:1,pass,nolog,ctl:ruleRemoveById=942290"

          SecRule REQUEST_URI "@rx ^/socket.io/" \
            "id:1000009,phase:1,pass,nolog,ctl:ruleRemoveById=980170,ctl:ruleRemoveById=920420"

          SecRule REQUEST_URI "@rx ^/remote.php/dav/" \
            "id:1000010,phase:1,pass,nolog,ctl:ruleEngine=Off"

          SecRule REQUEST_URI "@rx ^/api/auth/" \
            "id:1000011,phase:1,pass,nolog,ctl:ruleRemoveById=920420,ctl:ruleRemoveById=980170"

          SecRule REQUEST_URI "@rx ^/v1/volumes/pvc-" \
            "id:1000012,phase:1,pass,nolog,ctl:ruleRemoveById=932235,ctl:ruleRemoveById=932250"

          SecRule REQUEST_URI "@rx ^/Items" \
            "id:1000013,phase:1,pass,nolog,ctl:ruleRemoveById=942220,ctl:ruleRemoveById=980170"

          SecRule REQUEST_URI "@rx ^/apis/dashboard.grafana.app" \
            "id:1000014,phase:1,pass,nolog,ctl:ruleRemoveById=942290,ctl:ruleRemoveById=980170,ctl:ruleRemoveById=949110"

          SecRule REQUEST_URI "@rx ^/terraform-states" \
            "id:1000015,phase:1,pass,nolog,ctl:ruleRemoveById=200002,ctl:ruleRemoveById=980170,ctl:ruleRemoveById=920450"

          SecRule REQUEST_URI "@rx ^/upload" \
            "id:1000016,phase:1,pass,nolog,ctl:ruleRemoveById=932370,ctl:ruleRemoveById=980170"

          SecRule REQUEST_URI "@rx ^/api/resources" \
            "id:1000017,phase:1,pass,nolog,ctl:ruleRemoveById=911100,ctl:ruleRemoveById=942160,ctl:ruleRemoveById=949110,ctl:ruleRemoveById=980170"

          SecRule REQUEST_HEADERS:User-Agent "@rx ^argocd-client/" \
            "id:1000018,phase:1,pass,nolog,ctl:ruleRemoveById=920420"

          SecRule REQUEST_URI "@rx ^/auth/login_flow" \
            "id:1000019,phase:1,pass,nolog,ctl:ruleRemoveById=920420"

          SecRule REQUEST_URI "@rx ^/auth/" \
            "id:1000020,phase:1,pass,nolog,ctl:ruleRemoveById=943120"

          SecRule REQUEST_URI "@rx ^/api/websocket" \
            "id:1000021,phase:1,pass,nolog,ctl:ruleEngine=Off"

          SecRule REQUEST_URI "@rx ^/api/stream" \
            "id:1000022,phase:1,pass,nolog,ctl:ruleEngine=Off"

          SecRule REQUEST_URI "@rx ^/nix-cache" \
            "id:1000023,phase:1,pass,nolog,ctl:ruleEngine=Off"

          SecRule REQUEST_URI "@rx ^/api/ds/query" \
            "id:1000024,phase:1,pass,nolog,ctl:ruleRemoveById=942100,ctl:ruleRemoveById=942151,ctl:ruleRemoveById=949110,ctl:ruleRemoveById=980170"
    ok-server-script:
      data:
        index.ts: |
          Bun.serve({ async fetch(req: Request) { if (req.body) { for await (const chunk of req.body); } return new Response("OK", { status: 200 }); }, maxRequestBodySize: Infinity, });

  controllers:
    main:
      type: deployment
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        modsecurity:
          image:
            repository: docker.io/owasp/modsecurity-crs
            tag: 4.20.0-apache-alpine-202511100111@sha256:bd07bd19a2f5a97ffffedeb5c7e7960c04eac212152a0cb4d134290a5767ca6f
          env:
            TZ: Europe/Paris
            BACKEND: http://localhost:8082
            ACCESSLOG: /dev/null
            METRICSLOG: /dev/null
            PORT: "8081"
            SSL_PORT: "7443"
            DETECTION_PARANOIA: "1"
            BLOCKING_PARANOIA: "1"
            ANOMALY_INBOUND: "10"
            ANOMALY_OUTBOUND: "5"
            ALLOWED_METHODS: "GET HEAD POST PUT DELETE OPTIONS PROPFIND MKCOL MOVE COPY"
            ALLOWED_REQUEST_CONTENT_TYPE: |
              |application/x-www-form-urlencoded| |multipart/form-data|
              |multipart/related| |text/xml| |application/xml|
              |application/soap+xml| |application/json|
              |application/cloudevents+json|
              |application/cloudevents-batch+json| |application/octet-stream|
            MODSEC_REQ_BODY_LIMIT: "1073741824"
            MODSEC_REQ_BODY_NOFILES_LIMIT: "1073741824"
            MODSEC_RESP_BODY_LIMIT: "1073741824"
          ports:
            - name: http
              containerPort: 8081
          probes:
            liveness:
              enabled: true
              type: HTTP
            readiness:
              enabled: true
              type: HTTP

        ok-server:
          image:
            repository: docker.io/oven/bun
            tag: 1.3-alpine@sha256:5acc90a93e91ff07bf72aa90a7c9f0fa189765aec90b47bdbf2152d2196383c0
          env:
            TZ: Europe/Paris
            PORT: "8082"
          ports:
            - name: http
              containerPort: 8082
          probes:
            liveness:
              enabled: true
              type: HTTP
            readiness:
              enabled: true
              type: HTTP
          command: ["bun"]
          args: ["run", "/app/index.ts"]

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 8081

  persistence:
    modsecurity-config:
      enabled: true
      type: configMap
      identifier: modsecurity-request-exclusion-rules
      advancedMounts:
        main:
          modsecurity:
            - path: /etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
              subPath: REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf

    ok-server-config:
      enabled: true
      type: configMap
      identifier: ok-server-script
      advancedMounts:
        main:
          ok-server:
            - path: /app/index.ts
              subPath: index.ts
