apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-repo-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: velero-repo-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: velero/velero-repo-credentials
