apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k8s-versity-gw
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    kubernetes:
      remoteNamespace: versity-gw
      server:
        url: "https://kubernetes.default"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets
          key: ca.crt
      auth:
        serviceAccount:
          name: "k8s-secret-store"
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: versity-gw-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-versity-gw
  target:
    name: versity-gw-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config: |
          [default]
          aws_access_key_id = "{{"{{ .access_key }}"}}"
          aws_secret_access_key = "{{"{{ .secret_key }}"}}"
  data:
    - secretKey: access_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: versity-gw-credentials
        metadataPolicy: None
        property: ROOT_ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: versity-gw-credentials
        metadataPolicy: None
        property: ROOT_SECRET_KEY
