apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k8s-versity-gw
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    kubernetes:
      remoteNamespace: versity-gw
      server:
        url: "https://kubernetes.default"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets
          key: ca.crt
      auth:
        serviceAccount:
          name: "k8s-secret-store"
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: versity-gw-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: versity-gw-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: velero/versity-gw-credentials
