apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-telegram-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: argocd-notifications-controller-secret
    creationPolicy: Owner
  data:
    - secretKey: telegram-token 
      remoteRef: 
        key: argocd_notifications_telegram_token
