{{- range .Values.cnpgClusters }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k8s-{{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .namespace }}
      server:
        url: "https://kubernetes.default"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets
          key: ca.crt
      auth:
        serviceAccount:
          name: "k8s-secret-store"
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}-uri
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-{{ .namespace }}
  target:
    name: {{ .name }}-uri
  data:
    - secretKey: uri
      remoteRef:
        key: {{ .name }}-app
        property: uri
{{- end }}
