apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k8s-go-healthcheck
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    kubernetes:
      remoteNamespace: go-healthcheck
      server:
        url: "https://kubernetes.default"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets
          key: ca.crt
      auth:
        serviceAccount:
          name: "k8s-secret-store"
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go-healthcheck-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-go-healthcheck
  target:
    name: go-healthcheck-config
    template:
      engineVersion: v2
      data:
        config.yaml: |
          name: homelab
          version: 1.0
          timeout: 5
          httpClientCertPath: /etc/ssl/private/tls.crt
          httpClientKeyPath: /etc/ssl/private/tls.key
          httpStatusCodeErrorThreshold: 400
          targets:
            http:
              {{- range .Values.urls }}
              - {{ . }}
              {{- end }}

            postgresql:
              {{- range .Values.cnpgClusters }}
              - {{ `{{` }} .{{ .name | replace "-" "_" }}_uri {{ `}}` }}
              {{- end }}
  data:
    {{- range .Values.cnpgClusters }}
    - secretKey: {{ .name | replace "-" "_" }}_uri
      remoteRef:
        key: {{ .name }}-uri
        property: uri
    {{- end }}
