radicale:
  image:
    pullPolicy: IfNotPresent
    repository: docker.io/tomsquest/docker-radicale
    tag: 3.5.6.0@sha256:1cbb1e1fd7b789414338ceef789f01e30a9bdb84561b2da6eadddcc627a834e0

  securityContext:
    container:
      capabilities:
        add:
          - SETUID
          - SETGID
          - KILL
        drop:
          - ALL
      runAsUser: 2999
      runAsGroup: 2999
    pod:
      fsGroup: 2999

  service:
    main:
      ports:
        main:
          port: 5232
          protocol: http

  radicale:
    auth:
      delay: 1
      realm: Radicale - Password Required
      type: htpasswd
      users:
        - username: terence
          password: $2y$05$UvbxDPqbNPlLSFF/u1jHQOrsiYF55lo4NGsEVHYqxoDUt9J.QUwzu
    encoding:
      request: utf-8
      stock: utf-8
    logging:
      level: warning
      mask_passwords: true
    rights:
      type: owner_only
    server:
      max_connections: 8
      max_content_length: 100000000
      timeout: 30
    storage:
      max_sync_token_age: 2592000
      type: multifilesystem
    web:
      type: internal

  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              TAKE_FILE_OWNERSHIP: false

  persistence:
    config-file:
      enabled: true
      type: configmap
      objectName: radicale-config
      mountPath: /config/config
      subPath: config
      readOnly: false
    users:
      enabled: true
      type: configmap
      objectName: radicale-users
      mountPath: /config/users
      subPath: users
      readOnly: false
    data:
      enabled: true
      mountPath: /data
      size: 5Gi

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0,::/0"
      ingressClassName: "nginx"
      hosts:
        - host: &host radicale.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: radicale-tls
          hosts:
            - *host
      integrations:
        traefik:
          enabled: false
