apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-webhook-secret
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: argo-webhook-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: secret
      remoteRef:
        key: argocd_webhook_secret
