apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-github-repository-credentials
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: argo-github-repository-credentials
    creationPolicy: Owner
  data:
    - secretKey: sshPrivateKey 
      remoteRef: 
        key: argo_github_repository_credentials_ssh_private_key
    - secretKey: url 
      remoteRef: 
        key: argo_github_repository_credentials_url
