apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-pocket-id-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: argo-pocket-id-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  dataFrom:
    - extract:
        key: argocd/argo-pocket-id-credentials
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
