apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-github-repository-credentials
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: argo-github-repository-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: argocd/argo-github-repository-credentials
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
