apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-webhook-secret
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: argo-webhook-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  dataFrom:
    - extract:
        key: argocd/argo-webhook-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
