apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-pocket-id-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: argo-pocket-id-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: client-secret
      remoteRef:
        key: argo_pocket_id_client_secret
