apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-client-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: keycloak-client-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: dex.keycloak.clientSecret
      remoteRef:
        key: keycloak_argocd_client_secret
