# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
app-template:
  defaultPodOptions:
    automountServiceAccountToken: false
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    nodeSelector:
      kubernetes.io/hostname: homelab2

  controllers:
    jellyfin:
      type: deployment
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      pod:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      containers:
        jellyfin:
          image:
            repository: lscr.io/linuxserver/jellyfin
            tag: 10.10.6ubu2404-ls55@sha256:0b793d24dc3ec861e205ec3aceebe4021180d38a2f461522f1d83d992d4f053a
          env:
            TZ: Europe/Paris
          ports:
            - name: http
              containerPort: 8096
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /health
            readiness:
              enabled: true
              spec:
                httpGet:
                  port: http
                  path: /health
          securityContext:
            privileged: true

    jellyseerr:
      type: deployment
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        jellyseerr:
          image:
            repository: fallenbagel/jellyseerr
            tag: 2.5.0@sha256:92dc0eb9ba260a11886ac52c3a82c5490769238f120e6312a2793809842021a6
          env:
            TZ: Europe/Paris
          ports:
            - name: http
              containerPort: 5055
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /api/v1/status
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /api/v1/status
          securityContext:
            privileged: true

    sonarr:
      type: deployment
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        sonarr:
          image:
            repository: lscr.io/linuxserver/sonarr
            tag: 4.0.13.2932-ls274@sha256:b666479159c0ffc17d5c2281737c9a88d78afcaa0aa52cb441b46336f6feba31
          env:
            TZ: Europe/Paris
            PUID: 1000
            PGID: 1000
          ports:
            - name: http
              containerPort: 8989
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /ping
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /ping

    radarr:
      type: deployment
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: 5.19.3.9730-ls262@sha256:620189d67078ddcfeb7a4efa424eb62f827ef734ef1e56980768bf8efd73782a
          env:
            TZ: Europe/Paris
            PUID: 1000
            PGID: 1000
          ports:
            - name: http
              containerPort: 7878
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /ping
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /ping

    lidarr:
      type: deployment
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        lidarr:
          image:
            repository: lscr.io/linuxserver/lidarr
            tag: 2.9.6.4552-ls33@sha256:f3faffdc7143153f46c37388767975a131f0c57d4c73bdffa7338a1e9c5e7524
          env:
            TZ: Europe/Paris
            PUID: 1000
            PGID: 1000
          ports:
            - name: http
              containerPort: 8686
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /ping
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /ping

    prowlarr:
      type: deployment
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        prowlarr:
          image:
            repository: lscr.io/linuxserver/prowlarr
            tag: 1.32.2.4987-ls109@sha256:18e9801e4509e45873c1adb03adf0bf718743ff5147e19b4cdf7626f8bd2f752
          env:
            TZ: Europe/Paris
            PUID: 1000
            PGID: 1000
          ports:
            - name: http
              containerPort: 9696
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /ping
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /ping

    bazarr:
      type: deployment
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        bazarr:
          image:
            repository: lscr.io/linuxserver/bazarr
            tag: v1.5.1-ls295@sha256:0b3e1b888615cbd32cf879963d041abcf863d15160a9ace2928039a7b00590ef
          env:
            TZ: Europe/Paris
            PUID: 1000
            PGID: 1000
          ports:
            - name: http
              containerPort: 6767
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /ping
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /ping

    flaresolverr:
      type: deployment
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      pod:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      containers:
        flaresolverr:
          image:
            repository: ghcr.io/flaresolverr/flaresolverr
            tag: v3.3.21@sha256:f104ee51e5124d83cf3be9b37480649355d223f7d8f9e453d0d5ef06c6e3b31b
          env:
            TZ: Europe/Paris
          ports:
            - name: http
              containerPort: 8191
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /health
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /health

    butlarr:
      type: deployment
      strategy: Recreate
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        butlarr:
          image:
            repository: trimforce/butlarr
            tag: 1.2.2@sha256:79742266eabf6972ae5f82cadf083ddfff4c0313ace80a0593766e8d52352b38
          env:
            TZ: Europe/Paris
            BUTLARR_INTERACTIVE_SETUP: "false"
            BUTLARR_CONFIG_FILE: "/app/config.yaml"

    qbittorrent:
      type: deployment
      strategy: Recreate
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        qbittorrent:
          image:
            repository: lscr.io/linuxserver/qbittorrent
            tag: 5.0.4-r0-ls385@sha256:e96547d93403d8e7bdb5c0005da24511fffff58ebedb2c87e5c360779f69cd1a
          env:
            TZ: Europe/Paris
            PUID: 1000
            PGID: 1000
            TORRENTING_PORT: 6887
          ports:
            - name: http
              containerPort: 8080
            - name: torrent-tcp
              containerPort: 6887
          probes:
            liveness:
              enabled: true
              type: HTTP
            readiness:
              enabled: true
              type: HTTP

  service:
    jellyfin:
      controller: jellyfin
      type: ClusterIP
      ports:
        http:
          port: 8096
    jellyseerr:
      controller: jellyseerr
      type: ClusterIP
      ports:
        http:
          port: 5055
    sonarr:
      controller: sonarr
      type: ClusterIP
      ports:
        http:
          port: 8989
    radarr:
      controller: radarr
      type: ClusterIP
      ports:
        http:
          port: 7878
    lidarr:
      controller: lidarr
      type: ClusterIP
      ports:
        http:
          port: 8686
    prowlarr:
      controller: prowlarr
      type: ClusterIP
      ports:
        http:
          port: 9696
    bazarr:
      controller: bazarr
      type: ClusterIP
      ports:
        http:
          port: 6767
    flaresolverr:
      controller: flaresolverr
      type: ClusterIP
      ports:
        http:
          port: 8191
    qbittorrent:
      controller: qbittorrent
      type: ClusterIP
      ports:
        http:
          port: 8080
    qbittorrent-torrenting:
      controller: qbittorrent
      type: ClusterIP
      ports:
        torrent-tcp:
          port: 6887

  ingress:
    jellyfin:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
      className: "nginx"
      hosts:
        - host: &host jf.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: jellyfin
                port: http
      tls:
        - secretName: jellyfin-tls
          hosts:
            - *host

    jellyseerr:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        nginx.ingress.kubernetes.io/whitelist-source-range: "109.0.228.97/32,34.68.56.138/32"
      className: "nginx"
      hosts:
        - host: &host js.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: jellyseerr
                port: http
      tls:
        - secretName: jellyseerr-tls
          hosts:
            - *host

    sonarr:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        nginx.ingress.kubernetes.io/whitelist-source-range: "109.0.228.97/32,34.68.56.138/32"
      className: "nginx"
      hosts:
        - host: &host son.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: sonarr
                port: http
      tls:
        - secretName: sonarr-tls
          hosts:
            - *host

    radarr:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        nginx.ingress.kubernetes.io/whitelist-source-range: "109.0.228.97/32,34.68.56.138/32"
      className: "nginx"
      hosts:
        - host: &host rad.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: radarr
                port: http
      tls:
        - secretName: radarr-tls
          hosts:
            - *host

    lidarr:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        nginx.ingress.kubernetes.io/whitelist-source-range: "109.0.228.97/32,34.68.56.138/32"
      className: "nginx"
      hosts:
        - host: &host lid.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: lidarr
                port: http
      tls:
        - secretName: lidarr-tls
          hosts:
            - *host

    prowlarr:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        nginx.ingress.kubernetes.io/whitelist-source-range: "109.0.228.97/32,34.68.56.138/32"
      className: "nginx"
      hosts:
        - host: &host prow.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: prowlarr
                port: http
      tls:
        - secretName: prowlarr-tls
          hosts:
            - *host

    bazarr:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        nginx.ingress.kubernetes.io/whitelist-source-range: "109.0.228.97/32,34.68.56.138/32"
      className: "nginx"
      hosts:
        - host: &host baz.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: bazarr
                port: http
      tls:
        - secretName: bazarr-tls
          hosts:
            - *host

    qbittorrent:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        nginx.ingress.kubernetes.io/whitelist-source-range: "109.0.228.97/32,34.68.56.138/32"
      className: "nginx"
      hosts:
        - host: &host qb.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: qbittorrent
                port: http
      tls:
        - secretName: qbittorrent-tls
          hosts:
            - *host

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 600Gi
      advancedMounts:
        jellyfin:
          jellyfin:
            - path: /data/media
              subPath: media
        sonarr:
          sonarr:
            - path: /data
        radarr:
          radarr:
            - path: /data
        lidarr:
          lidarr:
            - path: /data
        bazarr:
          bazarr:
            - path: /data
        qbittorrent:
          qbittorrent:
            - path: /data/download
              subPath: download

    jellyfin-config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        jellyfin:
          jellyfin:
            - path: /config

    jellyfin-hwa:
      enabled: true
      type: hostPath
      hostPath: /dev/dri/renderD128
      hostPathType: "CharDevice"
      advancedMounts:
        jellyfin:
          jellyfin:
            - path: /dev/dri/renderD128

    jellyseerr-config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        jellyseerr:
          jellyseerr:
            - path: /app/config

    sonarr-config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        sonarr:
          sonarr:
            - path: /config

    radarr-config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        radarr:
          radarr:
            - path: /config

    lidarr-config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 100Mi
      advancedMounts:
        lidarr:
          lidarr:
            - path: /config

    butlarr-data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 100Mi
      advancedMounts:
        butlarr:
          butlarr:
            - path: /app/data

    butlarr-config-secret:
      enabled: true
      type: secret
      name: butlarr-config
      defaultMode: 0400
      items:
        - key: config.yaml
          path: config.yaml
      advancedMounts:
        butlarr:
          butlarr:
            - path: /app/config.yaml
              subPath: config.yaml

    qbittorrent-config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        qbittorrent:
          qbittorrent:
            - path: /config

    prowlarr-config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        prowlarr:
          prowlarr:
            - path: /config

    bazarr-config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 100Mi
      advancedMounts:
        bazarr:
          bazarr:
            - path: /config
