apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-wg-vm-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: gluetun-wg-vm-keys
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: arr-stack/gluetun-wg-vm-keys
