apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellystat-jwt-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: jellystat-jwt-secret
    creationPolicy: Owner
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: password
