apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rangemusique-api-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: rangemusique-api-keys
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: arr-stack/rangemusique-api-keys
