apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: slskd-config
  dataFrom:
    - extract:
        key: arr-stack/slskd-config
