apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slskd-password
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  refreshInterval: "0"
  target:
    name: slskd-password
    creationPolicy: Owner
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: password
