apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: soularr-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: soularr-config
    template:
      engineVersion: v2
      data:
        config.ini: |
          [Lidarr]
          api_key = {{ "{{ .lidarr_api_key }}" }}
          host_url = http://arr-stack-lidarr:8686
          download_dir = /data/download/slskd/complete

          [Slskd]
          api_key = {{ "{{ .slskd_api_key }}" }}
          host_url = http://arr-stack-slskd:5030
          url_base = /
          download_dir = /downloads
          delete_searches = True
          stalled_timeout = 3600

          [Release Settings]
          use_most_common_tracknum = True
          allow_multi_disc = True
          accepted_countries = Europe,Japan,United Kingdom,United States,[Worldwide],Australia,Canada
          accepted_formats = CD,Digital Media

          [Search Settings]
          search_timeout = 5000
          maximum_peer_queue = 50
          minimum_peer_upload_speed = 0
          minimum_filename_match_ratio = 0.5
          allowed_filetypes = flac 24/192,flac 16/44.1,flac,mp3 320,mp3
          ignored_users = ""
          search_for_tracks = True
          album_prepend_artist = False
          track_prepend_artist = True
          search_type = incrementing_page
          number_of_albums_to_grab = 1
          remove_wanted_on_failure = False
          title_blacklist = ""
          search_source = missing

          [Logging]
          level = INFO
          format = [%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s
          datefmt = %Y-%m-%dT%H:%M:%S%z

  data:
    - secretKey: lidarr_api_key
      remoteRef:
        key: lidarr_api_key
    - secretKey: slskd_api_key
      remoteRef:
        key: slskd_api_key
