apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: soularr-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: soularr-config
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: arr-stack/soularr-config
