apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: cloudflare-credentials
    creationPolicy: Owner
  data:
    - secretKey: cloudflare_api_token
      remoteRef:
        key: cloudflare_credentials_cloudflare_api_token
