apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-installation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: vaultwarden-installation
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: vaultwarden/vaultwarden-installation
