apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-installation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: vaultwarden-installation
    creationPolicy: Owner
  data:
    - secretKey: PUSH_INSTALLATION_ID
      remoteRef:
        key: vaultwarden_installation_id
    - secretKey: PUSH_INSTALLATION_KEY
      remoteRef:
        key: vaultwarden_installation_key
