apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: versity-gw-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: versity-gw-credentials
    creationPolicy: Owner
  data:
    - secretKey: ROOT_ACCESS_KEY
      remoteRef:
        key: versity_root_access_key
    - secretKey: ROOT_SECRET_KEY
      remoteRef:
        key: versity_root_secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-webdav-password
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  refreshInterval: "0"
  target:
    name: {{ .Release.Name }}-webdav-password
    creationPolicy: Owner
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: short-password
