apiVersion: v1
kind: PersistentVolume
metadata:
  name: mx500-homelab3
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mx500-homelab3/k8s-data
    server: 192.168.1.141
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    velero.io/exclude-from-backup: "true"
  name: mx500-homelab3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
  storageClassName: nfs
  volumeName: mx500-homelab3
