apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: nextcloud
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: nextcloud/nextcloud
