apiVersion: postgresql.cnpg.io/v1
kind: Publication
metadata:
  name: {{ .Release.Name }}
spec:
  cluster:
    name: {{ .Release.Name }}-cnpg-cluster-pg17
  dbname: {{ .Release.Name }}
  name: {{ .Release.Name }}
  target:
    allTables: true
  publicationReclaimPolicy: delete
---
apiVersion: postgresql.cnpg.io/v1
kind: Subscription
metadata:
  name: {{ .Release.Name }}
spec:
  cluster:
    name: {{ .Release.Name }}-cnpg-cluster-pg17-new
  dbname: {{ .Release.Name }}
  name: {{ .Release.Name }}
  externalClusterName: importSource
  publicationName: {{ .Release.Name }}
  subscriptionReclaimPolicy: delete
