apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-s3-creds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: cnpg-backup-s3-creds
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: versity-gw/versity-gw-credentials
        property: ROOT_ACCESS_KEY
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: versity-gw/versity-gw-credentials
        property: ROOT_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: niks3-api-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: api-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: niks3/api-token
        property: NIKS3_API_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: niks3-signing-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: signing-key
    creationPolicy: Owner
  data:
    - secretKey: signing-key
      remoteRef:
        key: niks3/signing-key
        property: signing-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: niks3-versity
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: versity-credentials
    creationPolicy: Owner
  data:
    - secretKey: access-key
      remoteRef:
        key: niks3/versity-credentials
        property: NIKS3_S3_ACCESS_KEY
    - secretKey: secret-key
      remoteRef:
        key: niks3/versity-credentials
        property: NIKS3_S3_SECRET_KEY
