image:
  repository: ghcr.io/k8s-at-home/qbittorrent
  tag: v4.4.2@sha256:61deadd1ec7865b5f1446943021b588915c24f09073358790f5415061d0a43dc

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true

autoscaling:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: home.terence.cloud
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    # The qBittorrent WebUI doesn't like to see gitlab.com as the referer, so we just strip this header out
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "Referer";
  hosts:
    - host: qbittorrent.terence.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: qbittorrent-tls
      hosts:
        - qbittorrent.terence.cloud

volumeMounts:
  - name: qbittorrent-configmap
    mountPath: /config/qBittorrent/qBittorrent.conf
    subPath: qBittorrent.conf
  - name: qbittorrent-config
    mountPath: /config/qBittorrent/
  - name: qbittorrent-downloads
    mountPath: /downloads

volumes:
  - name: qbittorrent-configmap
    configMap:
      name: qbittorrent-configmap
  - name: qbittorrent-config
    persistentVolumeClaim:
      claimName: qbittorrent-config
  - name: qbittorrent-downloads
    persistentVolumeClaim:
      claimName: qbittorrent-downloads

persistentVolumes:
  - name: qbittorrent-downloads
    accessMode: ReadWriteOnce
    size: 50Gi
  - name: qbittorrent-config
    accessMode: ReadWriteOnce
    size: 100Mi

configmaps:
  - name: qbittorrent-configmap
    data:
      # IMPORTANT : the settings below allow anybody to access the WebUI without authentication
      # WebUI\AuthSubnetWhitelist=0.0.0.0/0
      # WebUI\AuthSubnetWhitelistEnabled=true
      qBittorrent.conf: |
        [AutoRun]
        enabled=false
        program=

        [Core]
        AutoDeleteAddedTorrentFile=Never

        [LegalNotice]
        Accepted=true

        [Preferences]
        Advanced\RecheckOnCompletion=false
        Advanced\trackerPort=9000
        Advanced\AnonymousMode=true
        Bittorrent\Encryption=1
        Connection\PortRangeMin=6881
        Connection\ResolvePeerCountries=true
        Downloads\SavePath=/downloads/
        Downloads\TempPath=/downloads/temp/
        DynDNS\DomainName=changeme.dyndns.org
        DynDNS\Enabled=false
        DynDNS\Password=
        DynDNS\Service=0
        DynDNS\Username=
        General\Locale=
        MailNotification\email=
        MailNotification\enabled=false
        MailNotification\password=
        MailNotification\req_auth=true
        MailNotification\req_ssl=false
        MailNotification\sender=qBittorrent_notification@example.com
        MailNotification\smtp_server=smtp.changeme.com
        MailNotification\username=
        Queueing\QueueingEnabled=false
        WebUI\Address=*
        WebUI\AlternativeUIEnabled=false
        WebUI\AuthSubnetWhitelist=0.0.0.0/0
        WebUI\AuthSubnetWhitelistEnabled=true
        WebUI\BanDuration=3600
        WebUI\CSRFProtection=true
        WebUI\ClickjackingProtection=true
        WebUI\CustomHTTPHeaders=
        WebUI\CustomHTTPHeadersEnabled=false
        WebUI\HTTPS\CertificatePath=
        WebUI\HTTPS\Enabled=false
        WebUI\HTTPS\KeyPath=
        WebUI\HostHeaderValidation=false
        WebUI\LocalHostAuth=false
        WebUI\MaxAuthenticationFailCount=5
        WebUI\Port=8080
        WebUI\RootFolder=
        WebUI\SecureCookie=true
        WebUI\ServerDomains=*
        WebUI\SessionTimeout=3600
        WebUI\UseUPnP=false
        WebUI\Username=admin
