apiVersion: v2
name: nextcloud
description: A safe home for all your data
type: application
version: 0.1.0
dependencies:
  - name: nextcloud
    repository: https://nextcloud.github.io/helm/
    version: 6.6.7
  - name: cluster-local
    alias: cnpg-cluster-pg17
    repository: "file://../../charts/cnpg-cluster"
    version: 0.2.1
