external-dns:
  provider:
    name: cloudflare
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-credentials
          key: cloudflare_api_token
  serviceMonitor:
    enabled: true
  annotationFilter: external-dns.alpha.kubernetes.io/exclude notin (true)
