apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-credentials
spec:

  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: backup-credentials
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: backup_credentials_AWS_ACCESS_KEY_ID
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: backup_credentials_AWS_ENDPOINTS
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: backup_credentials_AWS_SECRET_ACCESS_KEY
