apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: longhorn
    role: alert-rules
  name: prometheus-longhorn-rules
spec:
  groups:
  - name: longhorn.rules
    rules:
    - alert: LonghornVolumeUsageCritical
      annotations:
        description: Longhorn volume {{ "{{$labels.volume}}" }} on {{ "{{$labels.node}}" }} is at {{ "{{$value}}%" }} used for
          more than 5 minutes.
        summary: Longhorn volume capacity is over 90% used.
      expr: 100 * (longhorn_volume_usage_bytes / longhorn_volume_capacity_bytes) > 90
      for: 5m
      labels:
        issue: Longhorn volume {{ "{{$labels.volume}}" }} usage on {{ "{{$labels.node}}" }} is critical.
        severity: critical
    - alert: LonghornDiskUsageCritical
      annotations:
        description: Longhorn disk {{ "{{$labels.disk}}" }} on {{ "{{$labels.node}}" }} is at {{ "{{$value}}%" }} used for
          more than 5 minutes.
        summary: Longhorn disk capacity is over 90% used.
      expr: 100 * (longhorn_disk_usage_bytes / longhorn_disk_capacity_bytes) > 90
      for: 5m
      labels:
        issue: Longhorn disk {{ "{{$labels.disk}}" }} usage on {{ "{{$labels.node}}" }} is critical.
        severity: critical
