# kubectl get secret client-auth -n cert-manager -o jsonpath='{.data.tls\.crt}' | base64 -d > client.crt
# kubectl get secret client-auth -n cert-manager -o jsonpath='{.data.tls\.key}' | base64 -d > client.key
# openssl pkcs12 -export -out client.p12 -inkey client.key -in client.crt
# cat client.crt client.key > client.pem
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-auth-ca
spec:
  isCA: true
  commonName: terence.cloud homelab CA (client auth)
  secretName: client-auth-ca
  duration: 87600h # 10 years
  renewBefore: 168h # 1 week
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: client-auth
spec:
  ca:
    secretName: client-auth-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-auth
spec:
  secretName: client-auth
  duration: 8760h # 1 year
  renewBefore: 168h # 1 week
  commonName: terence.cloud homelab certificate (client auth)
  usages:
    - digital signature
    - key encipherment
    - client auth
  issuerRef:
    name: client-auth
    kind: ClusterIssuer
