apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mtls-ca
spec:
  isCA: true
  commonName: mtls-ca
  secretName: mtls-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: mtls-ca
spec:
  ca:
    secretName: mtls-ca
