apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mtls-ca
spec:
  isCA: true
  commonName: mtls-ca
  secretName: mtls-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: mtls-ca
spec:
  ca:
    secretName: mtls-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mtls-client
spec:
  secretName: mtls-client
  duration: 8760h
  renewBefore: 720h
  commonName: mtls-client
  usages:
    - digital signature
    - key encipherment
    - client auth
  issuerRef:
    name: mtls-ca
    kind: ClusterIssuer
