# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
app-template:
  controllers:
    main:
      type: deployment
      labels:
        sablier.enable: "true"
        sablier.group: "{{ .Release.Name }}"
      containers:
        main:
          image:
            repository: mendhak/http-https-echo
            tag: 42@sha256:a265f55c86cb3baead76fdf379dc8e9e6440ed121874e101e60b833e05bce8d4
          ports:
            - name: http
              containerPort: 8080
          probes:
            liveness:
              enabled: true
              type: HTTP
            readiness:
              enabled: true
              type: HTTP

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 8080

  ingress:
    public:
      enabled: true
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.kubernetes.io/target: home.terence.cloud
        external-dns.kubernetes.io/cloudflare-proxied: "false"
        traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-sablier@kubernetescrd,traefik-modsecurity@kubernetescrd,anubis-anubis@kubernetescrd"
      hosts:
        - host: httpbin.terence.cloud
          paths:
            - path: /
              pathType: ImplementationSpecific
              service:
                identifier: main
                port: http
      tls:
        - secretName: httpbin-tls
          hosts:
            - httpbin.terence.cloud

  rawResources:
    sablier:
      enabled: true
      forceRename: sablier
      manifest:
        apiVersion: traefik.io/v1alpha1
        kind: Middleware
        spec:
          plugin:
            sablier:
              dynamic:
                displayName: "{{ .Release.Name }}"
                refreshFrequency: 5s
                showDetails: true
                theme: shuffle
              sablierUrl: http://sablier-sablier.sablier:10000
              sessionDuration: 10m
              ignoreUserAgent: curl
              group: "{{ .Release.Name }}"
