apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-better-auth-secret
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  refreshInterval: "0"
  target:
    name: {{ .Release.Name }}-better-auth-secret
    creationPolicy: Owner
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: password
