apiVersion: v2
name: oauth2-proxy
description: A reverse proxy that provides authentication with Google, Azure, OpenID Connect and many more identity providers
type: application
version: 0.1.0
dependencies:
  - name: oauth2-proxy
    repository: https://oauth2-proxy.github.io/manifests
    version: 7.7.10
