# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
app-template:
  defaultPodOptions:
    automountServiceAccountToken: false
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

  controllers:
    main:
      type: deployment
      strategy: RollingUpdate
      labels:
        sablier.enable: "false"
        sablier.group: "{{ .Release.Name }}"
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: ghcr.io/advplyr/audiobookshelf
            tag: 2.33.1
          env:
            TZ: Europe/Paris
            PORT: 13378
          ports:
            - name: http
              containerPort: 13378
          probes:
            liveness:
              enabled: true
              type: HTTP
            readiness:
              enabled: true
              type: HTTP
    shelfmark:
      type: deployment
      # labels:
      #   sablier.enable: "true"
      #   sablier.group: "calibre-web-downloader"
      annotations:
        reloader.stakater.com/auto: "true"
      pod:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          fsGroup: 0
      containers:
        main:
          image:
            repository: ghcr.io/calibrain/shelfmark
            tag: v1.2.1@sha256:5e00d47cccaa3b67234855d950d016c50691b78197a68adf15a624f6c08acee2
          env:
            TZ: Europe/Paris
            FLASK_PORT: 8084
            FLASK_DEBUG: false
            CLOUDFLARE_PROXY_URL: http://localhost:8000
            INGEST_DIR: /ebooks
            UID: "0"
            GID: "0"
            APP_ENV: prod
          ports:
            - name: http
              containerPort: 8084
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                failureThreshold: 10
                timeoutSeconds: 5
                httpGet:
                  port: http
                  path: /api/status
            readiness:
              enabled: true
              custom: true
              spec:
                failureThreshold: 10
                timeoutSeconds: 5
                httpGet:
                  port: http
                  path: /api/status
        cloudflare-bypass:
          image:
            repository: ghcr.io/sarperavci/cloudflarebypassforscraping
            tag: latest@sha256:c514191fad713649bceff1bb11d2cb7596aba031e9242e7c2e8ca8464d6ae32a
          env:
            TZ: Europe/Paris
          ports:
            - name: http
              containerPort: 8000
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: http
            readiness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: http

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 13378
    shelfmark:
      controller: shelfmark
      type: ClusterIP
      ports:
        http:
          port: 8084

  ingress:
    main:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        # traefik.ingress.kubernetes.io/router.tls.options: cert-manager-client-auth@kubernetescrd
        # traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-sablier@kubernetescrd,traefik-modsecurity@kubernetescrd"
        # external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      className: "traefik"
      hosts:
        - host: &host1 abs.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: abs-tls
          hosts:
            - *host1

    shelfmark:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        traefik.ingress.kubernetes.io/router.tls.options: cert-manager-client-auth@kubernetescrd
      className: "traefik"
      hosts:
        - host: &host2 shfm.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: shelfmark
                port: http
      tls:
        - secretName: shelfmark-tls
          hosts:
            - *host2

  persistence:
    config-abs:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 50Mi
      annotations:
        helm.sh/resource-policy: keep
        argocd.argoproj.io/sync-options: Delete=false
      advancedMounts:
        main:
          main:
            - path: /config
    config-shelfmark:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 50Mi
      annotations:
        helm.sh/resource-policy: keep
        argocd.argoproj.io/sync-options: Delete=false
      advancedMounts:
        shelfmark:
          main:
            - path: /config
    metadata:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 50Mi
      annotations:
        helm.sh/resource-policy: keep
        argocd.argoproj.io/sync-options: Delete=false
      advancedMounts:
        main:
          main:
            - path: /metadata
    audiobooks:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 5Gi
      annotations:
        helm.sh/resource-policy: keep
        argocd.argoproj.io/sync-options: Delete=false
      advancedMounts:
        main:
          main:
            - path: /audiobooks
    ebooks:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 5Gi
      annotations:
        helm.sh/resource-policy: keep
        argocd.argoproj.io/sync-options: Delete=false
      advancedMounts:
        main:
          main:
            - path: /ebooks
        shelfmark:
          main:
            - path: /ebooks
    podcasts:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 5Gi
      annotations:
        helm.sh/resource-policy: keep
        argocd.argoproj.io/sync-options: Delete=false
      advancedMounts:
        main:
          main:
            - path: /podcasts

  # rawResources:
  #   sablier:
  #     apiVersion: traefik.io/v1alpha1
  #     kind: Middleware
  #     spec:
  #       spec:
  #         plugin:
  #           sablier:
  #             dynamic:
  #               displayName: "{{ .Release.Name }}"
  #               refreshFrequency: 5s
  #               showDetails: true
  #               theme: shuffle
  #             sablierUrl: http://sablier-sablier.sablier:10000
  #             sessionDuration: 10m
  #             ignoreUserAgent: curl
  #             group: "{{ .Release.Name }}"
