apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret-key-base
spec:
  target:
    name: {{ .Release.Name }}-secret-key-base
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-synth-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: {{ .Release.Name }}-synth-api-key
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: synth_api_key
