loki:
  deploymentMode: SingleBinary
  loki:
    auth_enabled: false
    compactor:
      retention_enabled: true
      delete_request_store: filesystem
    ingester:
      chunk_encoding: snappy
    limits_config:
      retention_period: 30d
      allow_structured_metadata: true
    commonConfig:
      replication_factor: 1
    tracing:
      enabled: true
    storage:
      type: "filesystem"
      bucketNames:
        chunks: "i_have_to_be_defined" # https://github.com/grafana/loki/pull/19051
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: filesystem
          schema: v13
    querier:
      # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
      max_concurrent: 2
    rulerConfig:
      storage:
        type: local
        local:
          directory: /rules
      alertmanager_url: http://kube-prometheus-stack-alertmanager.monitoring.svc:9093
  chunksCache:
    writebackSizeLimit: 100MB
  gateway:
    service:
      labels:
        prometheus.io/service-monitor: "false"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []
  monitoring:
    serviceMonitor:
      enabled: true
    rules:
      enabled: true
  singleBinary:
    replicas: 1
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []
    persistence:
      annotations:
        helm.sh/resource-policy: keep
        argocd.argoproj.io/sync-options: Delete=false
      size: 20Gi

  sidecar:
    rules:
      folder: /rules/fake

  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0

  extraObjects:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: loki-rules-traefik-jail
        namespace: '{{ .Release.Namespace }}'
        labels:
          loki_rule: ""
      data:
        traefik-jail.yaml: |
          groups:
            - name: traefik-jail
              rules:
                - alert: TraefikJailBanned
                  expr: |
                    sum by (ip) (count_over_time({k8s_container_name="traefik"} |= "traefik-jail: banned" | regexp "ip=(?P<ip>[0-9.]+)" [5m])) > 0
                  for: 0m
                  labels:
                    severity: info
                    context: traefik
                  annotations:
                    summary: "IP {{ "{{ $labels.ip }}" }} banned by traefik-jail"
                    description: "IP {{ "{{ $labels.ip }}" }} was banned after exceeding the 4xx error threshold."

  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomCompactor:
    replicas: 0
  bloomGateway:
    replicas: 0
