# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
app-template:
  defaultPodOptions:
    automountServiceAccountToken: false
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

  configMaps:
    config:
      data:
        oidc.json: |
          {
            "providers": {
              "github": {
                "issuer": "https://token.actions.githubusercontent.com",
                "audience": "https://niks3.terence.cloud",
                "bound_claims": {
                  "repository_owner": ["cterence"]
                },
                "bound_subject": ["repo:cterence/nixos-config:*"]
              }
            }
          }

  controllers:
    main:
      type: deployment
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: ghcr.io/mic92/niks3
            tag: v1.7.0@sha256:d705d1b78d95db4da8643368f29aef431f422aefeaa87045661f6a02d8b409f5
          envFrom:
            - secretRef:
                name: versity-credentials
            - secretRef:
                name: api-token
          env:
            TZ: Europe/Paris
            NIKS3_DB:
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-cnpg-cluster-app"
                  key: fqdn-uri
            NIKS3_S3_ENDPOINT: versity.terence.cloud
            NIKS3_S3_BUCKET: nix-cache
            NIKS3_S3_REGION: us-east-1
            NIKS3_SIGN_KEY_PATHS: /secrets/signing-key
            NIKS3_ENABLE_READ_PROXY: "true"
            NIKS3_CACHE_URL: https://niks3.terence.cloud
          args:
            - --oidc-config
            - /config/oidc.json
          ports:
            - name: http
              containerPort: 5751
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /health
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /health
    gc:
      type: cronjob
      annotations:
        reloader.stakater.com/auto: "true"
      cronjob:
        schedule: "0 0 * * *"
        successfulJobsHistory: 1
        failedJobsHistory: 1
      containers:
        main:
          command: ["/bin/sh", "-c"]
          args: [
              "/bin/niks3 gc --older-than 168h --auth-token-path
              /secrets/auth-token-file/NIKS3_API_TOKEN",
            ]
          image:
            repository: ghcr.io/mic92/niks3
            tag: v1.7.0@sha256:d705d1b78d95db4da8643368f29aef431f422aefeaa87045661f6a02d8b409f5
          envFrom:
            - secretRef:
                name: versity-credentials
          env:
            TZ: Europe/Paris
            NIKS3_SERVER_URL: "http://niks3:5751"

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 5751

  ingress:
    main:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        # traefik.ingress.kubernetes.io/router.tls.options: cert-manager-client-auth@kubernetescrd
        # traefik.ingress.kubernetes.io/router.middlewares: "traefik-modsecurity@kubernetescrd"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
      className: "traefik"
      hosts:
        - host: &host niks3.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: niks3-tls
          hosts:
            - *host

  persistence:
    signing-key:
      type: secret
      name: signing-key
      advancedMounts:
        main:
          main:
            - path: /secrets/signing-key
              subPath: signing-key
              readOnly: true

    auth-token-file:
      type: secret
      name: api-token
      advancedMounts:
        gc:
          main:
            - path: /secrets/auth-token-file/NIKS3_API_TOKEN
              subPath: NIKS3_API_TOKEN
              readOnly: true

    oidc:
      type: configMap
      identifier: config
      advancedMounts:
        main:
          main:
            - path: /config/oidc.json
              subPath: oidc.json
              readOnly: true

  rawResources:
    cnpg-backup-s3-creds:
      enabled: true
      forceRename: cnpg-backup-s3-creds
      manifest:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        spec:
          secretStoreRef:
            kind: ClusterSecretStore
            name: openbao-secret-store
          target:
            name: cnpg-backup-s3-creds
            creationPolicy: Owner
          data:
            - secretKey: ACCESS_KEY_ID
              remoteRef:
                key: versity-gw/versity-gw-credentials
                property: ROOT_ACCESS_KEY
            - secretKey: ACCESS_SECRET_KEY
              remoteRef:
                key: versity-gw/versity-gw-credentials
                property: ROOT_SECRET_KEY
    api-token:
      enabled: true
      manifest:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        spec:
          secretStoreRef:
            kind: ClusterSecretStore
            name: openbao-secret-store
          target:
            name: api-token
            creationPolicy: Owner
          dataFrom:
            - extract:
                key: niks3/api-token
    signing-key:
      enabled: true
      manifest:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        spec:
          secretStoreRef:
            kind: ClusterSecretStore
            name: openbao-secret-store
          target:
            name: signing-key
            creationPolicy: Owner
          dataFrom:
            - extract:
                key: niks3/signing-key
    versity:
      enabled: true
      manifest:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        spec:
          secretStoreRef:
            kind: ClusterSecretStore
            name: openbao-secret-store
          target:
            name: versity-credentials
            creationPolicy: Owner
          dataFrom:
            - extract:
                key: niks3/versity-credentials

cnpg-cluster:
  type: postgresql
  mode: standalone
  version:
    postgresql: "18"
  cluster:
    instances: 1
    imageCatalogRef:
      kind: ClusterImageCatalog
      name: postgresql
    storage:
      size: 5Gi
    primaryUpdateMethod: switchover
    primaryUpdateStrategy: unsupervised
    logLevel: "info"
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
      prometheusRule:
        excludeRules:
          - CNPGClusterLogicalReplicationErrorsCritical
          - CNPGClusterLogicalReplicationErrors
          - CNPGClusterLogicalReplicationStoppedCritical
          - CNPGClusterLogicalReplicationStopped
          - CNPGClusterHACritical
          - CNPGClusterHAWarning
    postgresql: {}
    initdb:
      database: niks3
  backups:
    enabled: true
    endpointURL: http://versity-gw-nfs.versity-gw:7070
    destinationPath: s3://cnpg-backups/niks3
    provider: s3
    s3:
      region: us-east-1
      bucket: cnpg-backups
      path: /niks3
    secret:
      create: false
      name: cnpg-backup-s3-creds
    wal:
      compression: gzip
      encryption: ""
      maxParallel: 1
    data:
      compression: gzip
      encryption: ""
      jobs: 2
    scheduledBackups:
      - name: daily-backup
        schedule: "0 3 * * *"
        backupOwnerReference: self
        method: barmanObjectStore
    retentionPolicy: "7d"
