# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
app-template:
  controllers:
    # Configure the main controller
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

      containers:
        # Configure the main application container
        main:
          image:
            repository: ghcr.io/obeone/nfs-server
            tag: v2.2.3@sha256:932f4fa9d0f1f930a7670e58d920073cd136ec7ba62e82ef206d130544f065f6
          env:
            TZ: Europe/Paris
            NFS_EXPORT_0: "/elements *(rw,async,no_subtree_check)"
            NFS_DISABLE_VERSION_3: "true"
            NFS_LOG_LEVEL: DEBUG
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          ports:
            - name: nfs
              containerPort: 2049
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: 2049
            readiness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: 2049
  service:
    # Configure a service for the main application
    main:
      controller: main
      type: ClusterIP
      clusterIP: 10.100.10.21
      ports:
        nfs:
          port: 2049

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 900Gi
      storageClass: "-"
      globalMounts:
        - path: /elements
