# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
app-template:
  configMaps:
    config:
      data:
        TAILOUT_UI_PORT: "3000"
        TAILOUT_UI_ADDRESS: "0.0.0.0"
        # TODO: Allow setting these values from the UI
        TAILOUT_CREATE_SHUTDOWN: 30m
        TAILOUT_REGION: us-east-1

  controllers:
    server:
      type: deployment
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: ghcr.io/cterence/tailout
            tag: main@sha256:13a454ea6803d088b6a5597a997b4113a1446e61e3651485e3689a2634cd367e
          args:
            - ui
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                identifier: config
            - secretRef:
                name: tailout-credentials
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /health
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /health

  service:
    main:
      controller: server
      type: ClusterIP
      ports:
        http:
          port: 3000

  ingress:
    main:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
        nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Tailout"
        gethomepage.dev/description: "Create an exit node for your tailnet."
        gethomepage.dev/group: "Apps"
        gethomepage.dev/icon: "tailscale"
      hosts:
        - host: tailout.terence.cloud
          paths:
            - path: /
              pathType: ImplementationSpecific
              service:
                identifier: main
                port: http
      tls:
        - secretName: tailout-tls
          hosts:
            - tailout.terence.cloud
