apiVersion: v1
items:
  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: alertmanager-bot
    spec:
      secretStoreRef:
        kind: ClusterSecretStore
        name: gitlab-secret-store
      target:
        name: alertmanager-bot
        creationPolicy: Owner
      data:
        - secretKey: admin
          remoteRef:
            key: alertmanager_bot_admin
        - secretKey: token
          remoteRef:
            key: alertmanager_bot_token
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-bot
      name: alertmanager-bot
      namespace: monitoring
    spec:
      ports:
        - name: http
          port: 8080
          targetPort: 8080
      selector:
        app.kubernetes.io/name: alertmanager-bot
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-bot
      name: alertmanager-bot
      namespace: monitoring
    spec:
      podManagementPolicy: OrderedReady
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: alertmanager-bot
      serviceName: alertmanager-bot
      template:
        metadata:
          labels:
            app.kubernetes.io/name: alertmanager-bot
          name: alertmanager-bot
          namespace: monitoring
        spec:
          containers:
            - args:
                - --alertmanager.url=http://alertmanager-operated:9093
                - --log.level=info
                - --store=bolt
                - --bolt.path=/data/bot.db
              env:
                - name: TELEGRAM_ADMIN
                  valueFrom:
                    secretKeyRef:
                      key: admin
                      name: alertmanager-bot
                - name: TELEGRAM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: token
                      name: alertmanager-bot
              image: metalmatze/alertmanager-bot:0.4.3
              imagePullPolicy: IfNotPresent
              name: alertmanager-bot
              ports:
                - containerPort: 8080
                  name: http
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 25m
                  memory: 64Mi
              volumeMounts:
                - mountPath: /data
                  name: data
          restartPolicy: Always
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: alertmanager-bot-alertmanager-bot-0
      volumeClaimTemplates:
        - apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            labels:
              app.kubernetes.io/name: alertmanager-bot
            name: alertmanager-bot
            namespace: monitoring
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 200Mi
kind: List
