# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
app-template:
  defaultPodOptions:
    automountServiceAccountToken: false
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

  controllers:
    main:
      type: deployment
      strategy: RollingUpdate
      labels:
        sablier.enable: "false"
        sablier.group: "{{ .Release.Name }}"
      annotations:
        reloader.stakater.com/auto: "true"

      containers:
        main:
          image:
            repository: ghcr.io/cterence/tts9000
            tag: latest@sha256:316d414af78958a00a3c16a208eddd4e78bc0c389654b95f141384d821dc304b
          env:
            TZ: Europe/Paris
          envFrom:
            - secretRef:
                name: credentials
  persistence:
    generated:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      advancedMounts:
        main:
          main:
            - path: /app/generated

  rawResources:
    credentials:
      apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      forceRename: "credentials"
      annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
      spec:
        spec:
          secretStoreRef:
            kind: ClusterSecretStore
            name: openbao-secret-store
          target:
            name: "credentials"
            creationPolicy: Owner
          dataFrom:
            - extract:
                key: tts9000/credentials
                conversionStrategy: Default
                decodingStrategy: None
                metadataPolicy: None
                nullBytePolicy: Ignore
