apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-oauth2-credentials
spec:

  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: google-oauth2-credentials
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: google_oauth2_app_client_secret
    - secretKey: cookie-secret
      remoteRef:
        key: gitlab_oauth2_credentials_cookie_secret
