apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-oauth2-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: pocket-id-oauth2-credentials
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: oauth2_proxy_pocket_id_client_secret
    - secretKey: cookie-secret
      remoteRef:
        key: oauth2_proxy_pocket_id_cookie_secret
