apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lastfm-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: lastfm-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "scrobble-deduplicator/lastfm-credentials"
