app-template:
  controllers:
    main:
      type: deployment
      strategy: RollingUpdate
      labels:
        sablier.enable: "true"
        sablier.group: "{{ .Release.Name }}"
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: johngong/anki-sync-server
            tag: 26.08.1@sha256:7c6a89b5414a72d43c8e57f8079cd004e5c0f64ec071c7e02c1de7beefd60d1b
          env:
            TZ: Europe/Paris
          envFrom:
            - secretRef:
                name: anki-sync-server-creds
          ports:
            - name: http
              containerPort: 8080
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /health
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /health

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 8080

  ingress:
    main:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        traefik.ingress.kubernetes.io/router.middlewares: traefik-modsecurity@kubernetescrd,{{ .Release.Namespace }}-sablier@kubernetescrd
      className: "traefik"
      hosts:
        - host: &host ankss.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: anki-sync-server-tls
          hosts:
            - *host

  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      annotations:
        helm.sh/resource-policy: keep
        argocd.argoproj.io/sync-options: Delete=false
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /config

  rawResources:
    sablier:
      enabled: true
      forceRename: sablier
      manifest:
        apiVersion: traefik.io/v1alpha1
        kind: Middleware
        spec:
          plugin:
            sablier:
              dynamic:
                displayName: "{{ .Release.Name }}"
                refreshFrequency: 5s
                showDetails: true
                theme: shuffle
              sablierUrl: http://sablier-sablier.sablier:10000
              sessionDuration: 10m
              ignoreUserAgent: curl
              group: "{{ .Release.Name }}"
    anki-sync-server-creds:
      enabled: true
      forceRename: anki-sync-server-creds
      manifest:
        apiVersion: external-secrets.io/v1
        kind: ExternalSecret
        spec:
          secretStoreRef:
            kind: ClusterSecretStore
            name: gitlab-secret-store
          target:
            name: anki-sync-server-creds
            creationPolicy: Owner
            template:
              engineVersion: v2
              data:
                SYNC_USER1: '{{ "{{ .user }}:{{ .password }}" }}'
          data:
            - secretKey: user
              remoteRef:
                key: anki_sync_server_username
            - secretKey: password
              remoteRef:
                key: anki_sync_server_password
